### ISSUE TITLE
Quaternion multiplication

### ISSUE THREAD

**Issue by elton-choi** [PX4/Matrix#46]
I was reviewing px4 ecl library.

I found there is difference between matlab script and source code; Quaternion multiplication order..

and I was realized that this from Matrix library.

I think in this library quaternion multiplication is inversed..

`    /**
     * Quaternion multiplication operator
     *
     * @param q quaternion to multiply with
     * @return product
     */
    Quaternion operator*(const Quaternion &q) const
    {
        const Quaternion &p = *this;
        Quaternion r;
        r(0) = p(0) * q(0) - p(1) * q(1) - p(2) * q(2) - p(3) * q(3);
        r(1) = p(0) * q(1) + p(1) * q(0) - p(2) * q(3) + p(3) * q(2);
        r(2) = p(0) * q(2) + p(1) * q(3) + p(2) * q(0) - p(3) * q(1);
        r(3) = p(0) * q(3) - p(1) * q(2) + p(2) * q(1) + p(3) * q(0);
        return r;
    }`

I don't know why. I think it could errupt many mistakes..
Is there special reason for this inversion of multiplication order?

**Comment by jgoppert** [comment]
This was the convention used in px4/ecl originally. See the unit tests that show the impact on coordinate frame concatenation. Also see the pull request for the Hamilton quaternion convention. If ecl ever gets updated to work with  Hamilton quaternions, the matrix library will likely set Hamilton quaternions as the default.

**Comment by MaEtUgR** [comment]
Update: Since https://github.com/PX4/Matrix/pull/34 PX4/Matrix it's **fully Hamilton convention compliant**.
For the full 4 definition criterions see http://www.iri.upc.edu/people/jsola/JoanSola/objectes/notes/kinematics.pdf.
We still need to add easy readable documentation in the user guide.

Note that:
- Eigen uses Hamilton convention as well
- Matlab sadly has one difference dcm to quaternion conversion back and forth uses inverse quaternions because a famous Aircraft book has this convention
(see https://ch.mathworks.com/matlabcentral/answers/352465-what-is-the-aerospace-blockset-quaternion-convention)

FYI @priseborough @bresch
